global:
  # Console output log level 
  LogLevel: info
  
  # Debug logs file path
  LogFilePath: ./data/debug.log
  
  # Number of log files preserved (roughly equivalent to number of days)
  # Increase if you want to preserve log files for longer. This would require more disk space
  LogFileBackups: 10

  LogFormat: json
db:
  # Path to a persistent directory to store the node's database.
  Path: ./data/db

ssv:
  # The SSV network to join to
  # Mainnet = Network: mainnet (default)
  # Testnet (Goerli)  = Network: jato-v2
  # Testnet (Holesky) = Network: holesky
  Network: mainnet
  
  ValidatorOptions:
    # Whether to enable MEV block production. Requires the connected Beacon node to be MEV-enabled.
    BuilderProposals: true

eth2:
  # HTTP URL of the Beacon node to connect to.
  BeaconNodeAddr: http://consensus:5052 

eth1:
  # WebSocket URL of the Eth1 node to connect to.
#  ETH1Addr: ws://mainnet-eth1-ws.infra.internal # e.g. ws://example.url:8546/ws
  ETH1Addr: ws://execution:8546 #local

#p2p:
  # Optionally provide the external IP address of the node, if it cannot be automatically determined.
  # HostAddress: 192.168.1.1

  # Optionally override the default TCP & UDP ports of the node.
#  TcpPort: 13001
#  UdpPort: 12001

KeyStore:
  PrivateKeyFile: ./encrypted_private_key.json # e.g. ./encrypted_private_key.json
  PasswordFile: ./password # e.g. ./password

# This enables monitoring at the specified port, see https://docs.ssv.network/run-a-node/operator-node/maintenance/monitoring
MetricsAPIPort: 15000
